apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: ClusterIP
  ports:
    - name: http-listener
      protocol: TCP
      port: 8001
      targetPort: 8080
  selector:
    app: frontend